# Generated by Django 5.1.6 on 2025-02-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='Species',
        ),
        migrations.AddField(
            model_name='animals',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='animals',
            name='species',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
