# Generated by Django 5.1.6 on 2025-02-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_discription_animals_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Places',
        ),
    ]
